version: '1'

services:
  backend:
    build: .
    ports:
      - "3001:3001"
    container_name: backend-docker
    restart: always
    links:
      - db
  db:
    image: postgres:11.6-alpine
    ports:
      - "5432:5432"
    container_name: database-docker
    restart: always